#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuan5_QuanLyPhongMay
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyPhongMay")]
	public partial class QuanLyPhongMayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMayTinh(MayTinh instance);
    partial void UpdateMayTinh(MayTinh instance);
    partial void DeleteMayTinh(MayTinh instance);
    partial void InsertPhongMay(PhongMay instance);
    partial void UpdatePhongMay(PhongMay instance);
    partial void DeletePhongMay(PhongMay instance);
    #endregion
		
		public QuanLyPhongMayDataContext() : 
				base(global::Tuan5_QuanLyPhongMay.Properties.Settings.Default.QuanLyPhongMayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongMayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongMayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongMayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyPhongMayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MayTinh> MayTinhs
		{
			get
			{
				return this.GetTable<MayTinh>();
			}
		}
		
		public System.Data.Linq.Table<PhongMay> PhongMays
		{
			get
			{
				return this.GetTable<PhongMay>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MayTinh")]
	public partial class MayTinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _cpu;
		
		private string _hdd;
		
		private string _ram;
		
		private string _vga;
		
		private string _monitor;
		
		private System.Nullable<int> _idPhong;
		
		private EntityRef<PhongMay> _PhongMay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OncpuChanging(string value);
    partial void OncpuChanged();
    partial void OnhddChanging(string value);
    partial void OnhddChanged();
    partial void OnramChanging(string value);
    partial void OnramChanged();
    partial void OnvgaChanging(string value);
    partial void OnvgaChanged();
    partial void OnmonitorChanging(string value);
    partial void OnmonitorChanged();
    partial void OnidPhongChanging(System.Nullable<int> value);
    partial void OnidPhongChanged();
    #endregion
		
		public MayTinh()
		{
			this._PhongMay = default(EntityRef<PhongMay>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string cpu
		{
			get
			{
				return this._cpu;
			}
			set
			{
				if ((this._cpu != value))
				{
					this.OncpuChanging(value);
					this.SendPropertyChanging();
					this._cpu = value;
					this.SendPropertyChanged("cpu");
					this.OncpuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hdd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hdd
		{
			get
			{
				return this._hdd;
			}
			set
			{
				if ((this._hdd != value))
				{
					this.OnhddChanging(value);
					this.SendPropertyChanging();
					this._hdd = value;
					this.SendPropertyChanged("hdd");
					this.OnhddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ram", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ram
		{
			get
			{
				return this._ram;
			}
			set
			{
				if ((this._ram != value))
				{
					this.OnramChanging(value);
					this.SendPropertyChanging();
					this._ram = value;
					this.SendPropertyChanged("ram");
					this.OnramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vga", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vga
		{
			get
			{
				return this._vga;
			}
			set
			{
				if ((this._vga != value))
				{
					this.OnvgaChanging(value);
					this.SendPropertyChanging();
					this._vga = value;
					this.SendPropertyChanged("vga");
					this.OnvgaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monitor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string monitor
		{
			get
			{
				return this._monitor;
			}
			set
			{
				if ((this._monitor != value))
				{
					this.OnmonitorChanging(value);
					this.SendPropertyChanging();
					this._monitor = value;
					this.SendPropertyChanged("monitor");
					this.OnmonitorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPhong", DbType="Int")]
		public System.Nullable<int> idPhong
		{
			get
			{
				return this._idPhong;
			}
			set
			{
				if ((this._idPhong != value))
				{
					if (this._PhongMay.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidPhongChanging(value);
					this.SendPropertyChanging();
					this._idPhong = value;
					this.SendPropertyChanged("idPhong");
					this.OnidPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongMay_MayTinh", Storage="_PhongMay", ThisKey="idPhong", OtherKey="id", IsForeignKey=true)]
		public PhongMay PhongMay
		{
			get
			{
				return this._PhongMay.Entity;
			}
			set
			{
				PhongMay previousValue = this._PhongMay.Entity;
				if (((previousValue != value) 
							|| (this._PhongMay.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongMay.Entity = null;
						previousValue.MayTinhs.Remove(this);
					}
					this._PhongMay.Entity = value;
					if ((value != null))
					{
						value.MayTinhs.Add(this);
						this._idPhong = value.id;
					}
					else
					{
						this._idPhong = default(Nullable<int>);
					}
					this.SendPropertyChanged("PhongMay");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongMay")]
	public partial class PhongMay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _ten;
		
		private EntitySet<MayTinh> _MayTinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    #endregion
		
		public PhongMay()
		{
			this._MayTinhs = new EntitySet<MayTinh>(new Action<MayTinh>(this.attach_MayTinhs), new Action<MayTinh>(this.detach_MayTinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongMay_MayTinh", Storage="_MayTinhs", ThisKey="id", OtherKey="idPhong")]
		public EntitySet<MayTinh> MayTinhs
		{
			get
			{
				return this._MayTinhs;
			}
			set
			{
				this._MayTinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.PhongMay = this;
		}
		
		private void detach_MayTinhs(MayTinh entity)
		{
			this.SendPropertyChanging();
			entity.PhongMay = null;
		}
	}
}
#pragma warning restore 1591
